variables:
  RESOURCE_GROUP: "imake-resource"
  LOCATION: "southeastasia"
  ENVIRONMENT: "imake-env"
  WEB_NAME: "poc-encrypt-decrypt"
  ACR_NAME: "acrimakeimakedev"
  
  AZURE_TENANT_ID: "bef949f8-692d-43fc-8df3-81d9fc8780c4"
  AZURE_CLIENT_ID: "$AZURE_CLIENT_ID_VALUE" 
  AZURE_CLIENT_SECRET: "$AZURE_CLIENT_SECRET_VALUE"

  BUILD_ID: "${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"

  IMAGE_NAME: "$ACR_NAME.azurecr.io/$WEB_NAME"
  IMAGE_TAG: "v1.0.0"

  IP: "localhost"
  FRONT_VERSION: "1.0"
  DATABASE_TYPE: "postgres"
  DATABASE_USERNAME: "bsrc_ste_admin"
#รหัสผ่านดั้งเดิมใช้ไม่ได้ P@ssw0rd
  DATABASE_PASSWORD: "P%40ssw0rd"
  DATABASE_HOST: "157.245.148.217"
  DATABASE_PORT: "15432"
  DATABASE_NAME: "bsrc_ste_db"